language: perl
perl:
  - "5.18"
  - "5.20"
  - "5.22"
matrix:
  include:
    - perl: 5.22
    env: COVERAGE=1
before_install:
  - export NO_EDIT_CHANGES=1 AUTHOR_TESTING=0
  - eval $(curl https://travis-perl.github.io/init) --auto
